- name: Early Career Researchers
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - communication/communication
    - communication/comms-overview
    - communication/comms-overview/comms-overview-principles
    - collaboration/collaboration
    - collaboration/github-novice
    - collaboration/github-novice/github-novice-advanced
    - collaboration/leadership
  colour: blue
  description: Early Career Researchers (ECRs) are students, PhDs and early-stage
    postdocs who may not have a lot of experience in contributing to research
    projects from start to finish. This curated set of chapters will allow them
    to understand what best practices apply at different stages of development
    to ensure research reproducibility.
- name: Project Leaders
  files:
    - project-design/project-design
    - project-design/pd-overview
    - project-design/pd-overview/pd-overview-planning
    - project-design/pd-overview/pd-overview-repro
    - project-design/pd-overview/pd-overview-methods
    - project-design/pd-overview/pd-overview-version
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/overview/overview-definitions
    - reproducible-research/overview/overview-benefit
    - reproducible-research/overview/overview-resources
    - reproducible-research/overview/overview-barriers
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: purple
  description: Project leaders are people who are responsible for project
    planning, resource allocation and other decision-making for and with the
    involvement of their project team. This curated set of chapters will point
    them to relevant tools and practices that they can use for managing their
    projects while ensuring transparency, reproducibility, collaboration and
    ethical practices throughout the lifecycle of research.
- name: Research Software Engineers
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/open
    - reproducible-research/open/open-data
    - reproducible-research/open/open-source
  colour: white
  description: Research Software Engineers are programmers with scientific
    backgrounds who play crucial roles in projects involving data and
    technology. This curated set of chapters will point them to open source and
    reproducibility practices important for working with data and developing
    software tools.
- name: Software Citation
  files:
    - reproducible-research/reproducible-research
    - reproducible-research/overview
    - reproducible-research/open
    - reproducible-research/open/open-source
    - reproducible-research/rdm
    - reproducible-research/rdm/rdm-metadata
    - reproducible-research/rdm/rdm-sharing
    - reproducible-research/compendia
    - reproducible-research/code-reuse
    - reproducible-research/code-reuse/code-reuse-overview
    - reproducible-research/licensing
    - reproducible-research/licensing/licensing-software
    - communications/research-objects
    - communications/citable
    - communication/citable/citable-steps
    - communication/citable/citable-cite
    - communication/citable/citable-cff
    - communication/citable/citable-cffinit
    - communication/citable/citable-linking
    - communication/citable/citable-orcid
    - communication/citable/citable-resources
    - collaboration/github-novice
    - collaboration/shared-ownership
    - collaboration/shared-ownership/shared-ownership-models
  colour: green
  description: All sectors, from research to government, strongly rely upon the
    use of the software. This curated set of chapters guides the sharing and
    citation of software components from source code to computational workflows
    and executables while attributing all contributors fairly.
